<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EER" nsURI="http://EER/1.0" nsPrefix="EER">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//AttributedNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributedNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PrimaryKeysOCL"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="PrimaryKeysOCL" value="&#xA;&#x9;&#x9;&#x9;self.isSpecializedBy -> size() = 0 and &#xA;&#x9;&#x9;&#x9;self.specializes -> size() = 0 &#xA;&#x9;&#x9;&#x9;  implies  self.primaryKey -> size() = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKey" eType="#//CandidateKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="candidateKey" lowerBound="1"
        upperBound="-1" eType="#//CandidateKey" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencyRelationships"
        upperBound="-1" eType="#//DependencyRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSpecializedBy" upperBound="-1"
        eType="#//SpecializationRelationship" containment="true" eOpposite="#//SpecializationRelationship/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specializes" upperBound="-1"
        eType="#//GeneralizationRelationship" containment="true" eOpposite="#//GeneralizationRelationship/child"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeakEntity" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusive" eSuperTypes="#//Constraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SourceTarget"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="SourceTarget" value="&#xA;&#x9;&#x9;&#x9;self.target &lt;> self.source"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Participant" eOpposite="#//Participant/exclusiveConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Participant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusiveness" eSuperTypes="#//Constraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SourceTarget"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="SourceTarget" value="&#xA;&#x9;&#x9;&#x9;self.target &lt;> self.source"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Participant" eOpposite="#//Participant/inclusivenessConstraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusion" eSuperTypes="#//Constraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SourceTarget"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="SourceTarget" value="&#xA;&#x9;&#x9;&#x9;self.target &lt;> self.source"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Relationship" eOpposite="#//Relationship/exclusionConstraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Relationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusion" eSuperTypes="#//Constraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SourceTarget"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="SourceTarget" value="&#xA;&#x9;&#x9;&#x9;self.target &lt;> self.source"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Relationship" eOpposite="#//Relationship/inclusionConstraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Relationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CandidateKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="singlesAttributes" lowerBound="2"
        upperBound="-1" eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationType" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
        upperBound="-1" eType="#//EnumeratedLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRelationship" abstract="true"
      eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" lowerBound="2"
        upperBound="-1" eType="#//Participant" containment="true" eOpposite="#//Participant/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//AbstractRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exclusionConstraints" upperBound="-1"
        eType="#//Exclusion" containment="true" eOpposite="#//Exclusion/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inclusionConstraints" upperBound="-1"
        eType="#//Inclusion" containment="true" eOpposite="#//Inclusion/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependencyRelationship" eSuperTypes="#//AbstractRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DependencyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="#//AbstractParticipant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractRelationship" eOpposite="#//AbstractRelationship/participants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exclusiveConstraint" upperBound="-1"
        eType="#//Exclusive" containment="true" eOpposite="#//Exclusive/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inclusivenessConstraint"
        upperBound="-1" eType="#//Inclusiveness" containment="true" eOpposite="#//Inclusiveness/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//AttributedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//SpecializationRelationship" eOpposite="#//SpecializationRelationship/relationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childs" lowerBound="1"
        upperBound="-1" eType="#//GeneralizationRelationship" eOpposite="#//GeneralizationRelationship/relationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//Attribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GeneralizationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecializationRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Entity" eOpposite="#//Entity/isSpecializedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationship" lowerBound="1"
        eType="#//Generalization" eOpposite="#//Generalization/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralizationRelationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationship" lowerBound="1"
        eType="#//Generalization" eOpposite="#//Generalization/childs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//Entity"
        eOpposite="#//Entity/specializes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DependencyType">
    <eLiterals name="ID"/>
    <eLiterals name="E" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GeneralizationType">
    <eLiterals name="totalOverlapping"/>
    <eLiterals name="totalDisjoint" value="1"/>
    <eLiterals name="partialOverlapping" value="2"/>
    <eLiterals name="partialDisjoint" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractParticipant" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregationParticipant" eSuperTypes="#//AbstractParticipant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Aggregation" eOpposite="#//Aggregation/participants"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//AttributedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//AttributedNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" lowerBound="1"
        upperBound="-1" eType="#//AggregationParticipant" containment="true" eOpposite="#//AggregationParticipant/source"/>
  </eClassifiers>
</ecore:EPackage>
