package fr.unice.i3s.sigma.examples.uml.support


import org.eclipse.uml2.uml.UMLPackage;

trait UmlPackageScalaSupport
  extends AbstractionScalaSupport with
  DependencyScalaSupport with
  PackageableElementScalaSupport with
  ParameterableElementScalaSupport with
  ElementScalaSupport with
  CommentScalaSupport with
  StereotypeScalaSupport with
  ClassScalaSupport with
  EncapsulatedClassifierScalaSupport with
  StructuredClassifierScalaSupport with
  ClassifierScalaSupport with
  NamespaceScalaSupport with
  NamedElementScalaSupport with
  StringExpressionScalaSupport with
  ExpressionScalaSupport with
  ValueSpecificationScalaSupport with
  TypedElementScalaSupport with
  TypeScalaSupport with
  PackageScalaSupport with
  TemplateableElementScalaSupport with
  TemplateSignatureScalaSupport with
  TemplateParameterScalaSupport with
  TemplateBindingScalaSupport with
  DirectedRelationshipScalaSupport with
  RelationshipScalaSupport with
  TemplateParameterSubstitutionScalaSupport with
  PackageMergeScalaSupport with
  ProfileApplicationScalaSupport with
  ProfileScalaSupport with
  ElementImportScalaSupport with
  PackageImportScalaSupport with
  ExtensionScalaSupport with
  AssociationScalaSupport with
  PropertyScalaSupport with
  StructuralFeatureScalaSupport with
  MultiplicityElementScalaSupport with
  FeatureScalaSupport with
  RedefinableElementScalaSupport with
  ConnectableElementScalaSupport with
  ConnectorEndScalaSupport with
  ConnectableElementTemplateParameterScalaSupport with
  DeploymentTargetScalaSupport with
  DeploymentScalaSupport with
  DeploymentSpecificationScalaSupport with
  ArtifactScalaSupport with
  DeployedArtifactScalaSupport with
  ManifestationScalaSupport with
  OperationScalaSupport with
  BehavioralFeatureScalaSupport with
  BehaviorScalaSupport with
  BehavioredClassifierScalaSupport with
  InterfaceRealizationScalaSupport with
  RealizationScalaSupport with
  InterfaceScalaSupport with
  ReceptionScalaSupport with
  SignalScalaSupport with
  ProtocolStateMachineScalaSupport with
  StateMachineScalaSupport with
  PseudostateScalaSupport with
  VertexScalaSupport with
  RegionScalaSupport with
  StateScalaSupport with
  ConnectionPointReferenceScalaSupport with
  TriggerScalaSupport with
  EventScalaSupport with
  PortScalaSupport with
  ConstraintScalaSupport with
  TransitionScalaSupport with
  ProtocolConformanceScalaSupport with
  ParameterScalaSupport with
  ParameterSetScalaSupport with
  DataTypeScalaSupport with
  OperationTemplateParameterScalaSupport with
  ExtensionEndScalaSupport with
  ModelScalaSupport with
  EnumerationScalaSupport with
  EnumerationLiteralScalaSupport with
  InstanceSpecificationScalaSupport with
  SlotScalaSupport with
  PrimitiveTypeScalaSupport with
  UsageScalaSupport with
  CollaborationUseScalaSupport with
  CollaborationScalaSupport with
  GeneralizationScalaSupport with
  GeneralizationSetScalaSupport with
  RedefinableTemplateSignatureScalaSupport with
  UseCaseScalaSupport with
  ExtendScalaSupport with
  ExtensionPointScalaSupport with
  IncludeScalaSupport with
  SubstitutionScalaSupport with
  ClassifierTemplateParameterScalaSupport with
  ConnectorScalaSupport with
  ImageScalaSupport with
  OpaqueExpressionScalaSupport with
  AcceptCallActionScalaSupport with
  AcceptEventActionScalaSupport with
  ActionScalaSupport with
  ExecutableNodeScalaSupport with
  ActivityNodeScalaSupport with
  ActivityScalaSupport with
  ActivityGroupScalaSupport with
  ActivityEdgeScalaSupport with
  ActivityPartitionScalaSupport with
  StructuredActivityNodeScalaSupport with
  InputPinScalaSupport with
  PinScalaSupport with
  ObjectNodeScalaSupport with
  OutputPinScalaSupport with
  VariableScalaSupport with
  InterruptibleActivityRegionScalaSupport with
  ExceptionHandlerScalaSupport with
  ActionExecutionSpecificationScalaSupport with
  ExecutionSpecificationScalaSupport with
  InteractionFragmentScalaSupport with
  LifelineScalaSupport with
  PartDecompositionScalaSupport with
  InteractionUseScalaSupport with
  GateScalaSupport with
  MessageEndScalaSupport with
  MessageScalaSupport with
  InteractionScalaSupport with
  InteractionOperandScalaSupport with
  InteractionConstraintScalaSupport with
  GeneralOrderingScalaSupport with
  OccurrenceSpecificationScalaSupport with
  ActionInputPinScalaSupport with
  ActivityFinalNodeScalaSupport with
  FinalNodeScalaSupport with
  ControlNodeScalaSupport with
  ActivityParameterNodeScalaSupport with
  ActorScalaSupport with
  AddStructuralFeatureValueActionScalaSupport with
  WriteStructuralFeatureActionScalaSupport with
  StructuralFeatureActionScalaSupport with
  AddVariableValueActionScalaSupport with
  WriteVariableActionScalaSupport with
  VariableActionScalaSupport with
  AnyReceiveEventScalaSupport with
  MessageEventScalaSupport with
  AssociationClassScalaSupport with
  BehaviorExecutionSpecificationScalaSupport with
  BroadcastSignalActionScalaSupport with
  InvocationActionScalaSupport with
  CallActionScalaSupport with
  CallBehaviorActionScalaSupport with
  CallEventScalaSupport with
  CallOperationActionScalaSupport with
  CentralBufferNodeScalaSupport with
  ChangeEventScalaSupport with
  ClauseScalaSupport with
  ClearAssociationActionScalaSupport with
  ClearStructuralFeatureActionScalaSupport with
  ClearVariableActionScalaSupport with
  CombinedFragmentScalaSupport with
  CommunicationPathScalaSupport with
  ComponentScalaSupport with
  ComponentRealizationScalaSupport with
  ConditionalNodeScalaSupport with
  ConsiderIgnoreFragmentScalaSupport with
  ContinuationScalaSupport with
  ControlFlowScalaSupport with
  CreateLinkActionScalaSupport with
  WriteLinkActionScalaSupport with
  LinkActionScalaSupport with
  LinkEndDataScalaSupport with
  QualifierValueScalaSupport with
  LinkEndCreationDataScalaSupport with
  CreateLinkObjectActionScalaSupport with
  CreateObjectActionScalaSupport with
  DataStoreNodeScalaSupport with
  DecisionNodeScalaSupport with
  ObjectFlowScalaSupport with
  DestroyLinkActionScalaSupport with
  LinkEndDestructionDataScalaSupport with
  DestroyObjectActionScalaSupport with
  DestructionOccurrenceSpecificationScalaSupport with
  MessageOccurrenceSpecificationScalaSupport with
  DeviceScalaSupport with
  NodeScalaSupport with
  DurationScalaSupport with
  ObservationScalaSupport with
  IntervalConstraintScalaSupport with
  IntervalScalaSupport with
  DurationIntervalScalaSupport with
  ExecutionEnvironmentScalaSupport with
  ExecutionOccurrenceSpecificationScalaSupport with
  ExpansionNodeScalaSupport with
  ExpansionRegionScalaSupport with
  FinalStateScalaSupport with
  FlowFinalNodeScalaSupport with
  ForkNodeScalaSupport with
  FunctionBehaviorScalaSupport with
  OpaqueBehaviorScalaSupport with
  InformationFlowScalaSupport with
  InformationItemScalaSupport with
  InitialNodeScalaSupport with
  InstanceValueScalaSupport with
  JoinNodeScalaSupport with
  LiteralBooleanScalaSupport with
  LiteralSpecificationScalaSupport with
  LiteralIntegerScalaSupport with
  LiteralNullScalaSupport with
  LiteralRealScalaSupport with
  LiteralStringScalaSupport with
  LiteralUnlimitedNaturalScalaSupport with
  LoopNodeScalaSupport with
  MergeNodeScalaSupport with
  OpaqueActionScalaSupport with
  ProtocolTransitionScalaSupport with
  RaiseExceptionActionScalaSupport with
  ReadExtentActionScalaSupport with
  ReadIsClassifiedObjectActionScalaSupport with
  ReadLinkActionScalaSupport with
  ReadLinkObjectEndActionScalaSupport with
  ReadLinkObjectEndQualifierActionScalaSupport with
  ReadSelfActionScalaSupport with
  ReadStructuralFeatureActionScalaSupport with
  ReadVariableActionScalaSupport with
  ReclassifyObjectActionScalaSupport with
  ReduceActionScalaSupport with
  RemoveStructuralFeatureValueActionScalaSupport with
  RemoveVariableValueActionScalaSupport with
  ReplyActionScalaSupport with
  SendObjectActionScalaSupport with
  SendSignalActionScalaSupport with
  SequenceNodeScalaSupport with
  SignalEventScalaSupport with
  StartClassifierBehaviorActionScalaSupport with
  StartObjectBehaviorActionScalaSupport with
  StateInvariantScalaSupport with
  TestIdentityActionScalaSupport with
  TimeConstraintScalaSupport with
  TimeIntervalScalaSupport with
  TimeExpressionScalaSupport with
  TimeEventScalaSupport with
  TimeObservationScalaSupport with
  UnmarshallActionScalaSupport with
  ValuePinScalaSupport with
  ValueSpecificationActionScalaSupport

object UmlPackageScalaSupport extends UmlPackageScalaSupport {
  
  private[this] val pkg = UMLPackage.eINSTANCE
}