<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodel"
    nsURI="http://www.i3s.unice.fr/Sigma/TestModel" nsPrefix="testmodel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.i3s.unice.fr/Sigma"/>
    <details key="settingDelegates" value="http://www.i3s.unice.fr/Sigma"/>
    <details key="validationDelegates" value="http://www.i3s.unice.fr/Sigma"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass">
    <eAnnotations source="http://www.i3s.unice.fr/Sigma">
      <details key="delegate" value="testmodel.delegates.TestClassDelegate"/>
      <details key="A" value=""/>
      <details key="B" value=""/>
      <details key="C" value=""/>
      <details key="D" value=""/>
      <details key="E" value=""/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="A B C D E F"/>
    </eAnnotations>
    <eOperations name="method" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.i3s.unice.fr/Sigma"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedAttribute" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.i3s.unice.fr/Sigma"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
