<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tm"
    nsURI="http://www.i3s.unice.fr/Sigma/Tests" nsPrefix="tm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.i3s.unice.fr/Sigma"/>
    <details key="settingDelegates" value="http://www.i3s.unice.fr/Sigma"/>
    <details key="validationDelegates" value="http://www.i3s.unice.fr/Sigma"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass">
    <eAnnotations source="http://www.i3s.unice.fr/Sigma">
      <details key="delegate" value="tm.delegates.TestClassDelegate"/>
      <details key="NonZero" value=""/>
      <details key="SmallerThan100" value=""/>
      <details key="Divides64" value=""/>
      <details key="WithMessage" value=""/>
      <details key="WithQuickFix" value=""/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonZero SmallerThan100 Divides64 WithMessage WithQuickFix"/>
    </eAnnotations>
    <eOperations name="getSquare" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.i3s.unice.fr/Sigma"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedAttribute" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.i3s.unice.fr/Sigma"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
